-- CS336 Project 1 - Group 28
-- Step 2: write Preliminary back out to a CSV that should be byte-for-byte
-- identical to the original downloaded file (sequence_number blanked back out,
-- original row order restored via ORDER BY sequence_number).
--
-- Run with:  psql -f 02_export_to_csv.sql
-- or from inside psql:  \i 02_export_to_csv.sql
-- Then verify with:  diff hmda_2017_nj_all-records_labels.csv reconstructed.csv
--
-- NOTES:
-- - \copy is a psql backslash (meta-)command, not plain SQL, so unlike a
--   regular multi-line SQL statement it must be entirely on one line -- psql
--   stops reading it at the first newline. Keep this as a single line.
-- - The output column list re-aliases sequence_number to NULL, which shadows
--   the real table column of the same name. Postgres resolves a bare ORDER BY
--   name against an output alias before an input column, so `ORDER BY
--   sequence_number` would silently sort by that constant NULL (a no-op) and
--   not actually restore original row order. Table-qualifying it as
--   p.sequence_number forces it to resolve to the real column instead.
-- - The source file double-quotes every field, including blank/numeric ones.
--   Postgres's COPY TO only quotes fields that need it (comma/quote/newline)
--   unless told otherwise, so FORCE_QUOTE * is required to match the
--   original's formatting for a byte-identical round trip. One exception:
--   Postgres never quotes a NULL, even with FORCE_QUOTE, so a blank field
--   that round-trips through SQL NULL comes back out as an unquoted empty
--   field instead of "" -- this is a hard Postgres limitation, not a bug in
--   this script, and should just be noted under Known Issues.

\copy (SELECT as_of_year, respondent_id, agency_name, agency_abbr, agency_code, loan_type_name, loan_type, property_type_name, property_type, loan_purpose_name, loan_purpose, owner_occupancy_name, owner_occupancy, loan_amount_000s, preapproval_name, preapproval, action_taken_name, action_taken, msamd_name, msamd, state_name, state_abbr, state_code, county_name, county_code, census_tract_number, applicant_ethnicity_name, applicant_ethnicity, co_applicant_ethnicity_name, co_applicant_ethnicity, applicant_race_name_1, applicant_race_1, applicant_race_name_2, applicant_race_2, applicant_race_name_3, applicant_race_3, applicant_race_name_4, applicant_race_4, applicant_race_name_5, applicant_race_5, co_applicant_race_name_1, co_applicant_race_1, co_applicant_race_name_2, co_applicant_race_2, co_applicant_race_name_3, co_applicant_race_3, co_applicant_race_name_4, co_applicant_race_4, co_applicant_race_name_5, co_applicant_race_5, applicant_sex_name, applicant_sex, co_applicant_sex_name, co_applicant_sex, applicant_income_000s, purchaser_type_name, purchaser_type, denial_reason_name_1, denial_reason_1, denial_reason_name_2, denial_reason_2, denial_reason_name_3, denial_reason_3, rate_spread, hoepa_status_name, hoepa_status, lien_status_name, lien_status, edit_status_name, edit_status, NULL::text AS sequence_number, population, minority_population, hud_median_family_income, tract_to_msamd_income, number_of_owner_occupied_units, number_of_1_to_4_family_units, application_date_indicator FROM Preliminary p ORDER BY p.sequence_number) TO 'reconstructed.csv' WITH (FORMAT csv, HEADER true, FORCE_QUOTE *)
